name: Blog Auto Posting

on:
  schedule:
    # 한국 시간(KST) 기준 매일 오전 8시, 오후 5시에 실행 (UTC 기준 23:00, 08:00)
    - cron: '0 23,8 * * *'
  workflow_dispatch: # Actions 탭에서 수동으로 실행 가능

jobs:
  build-and-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run automation script
        run: python main.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TISTORY_ACCESS_TOKEN: ${{ secrets.TISTORY_ACCESS_TOKEN }}
          TISTORY_BLOG_NAME: ${{ secrets.TISTORY_BLOG_NAME }}
