name: Blog Auto Posting

on:
  schedule:
    # 한국 시간(KST) 기준 매일 오전 8시에 실행 (UTC 기준 23:00)
    - cron: '0 23 * * *'
  workflow_dispatch: # Actions 탭에서 수동으로 실행 가능

jobs:
  build-and-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 부동산 블로그 포스팅
        run: python src/tistory/real_estate_posting.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TISTORY_ID: ${{ secrets.TISTORY_ID }}
          TISTORY_PW: ${{ secrets.TISTORY_PW }}
          TISTORY_BLOG_NAME: ${{ secrets.TISTORY_BLOG_NAME }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
